server:
  port: 8080

spring:

  datasource:
#    url: jdbc:mysql://localhost:3306/library-management?serverTimezone=GMT%2b8
    url: jdbc:mysql://10.23.127.99:3306/library-management?serverTimezone=GMT%2b8
    username: root
    password: Hzx492357816
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
#    host: localhost
    host: 10.23.127.99
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    id-type: auto

